baseURL = 'https://leetcode.ricky-hu.com/'
languageCode = 'en-us'
title = "Leetcode-Solutions"
theme = 'archie'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "toggle"
useCDN = false
subtitle = "Ricky's Leetcode Solutions"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ricky9667"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/ricky9667/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Problems"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
